# Generated by Django 4.1.6 on 2023-02-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=200)),
                ('teampic', models.ImageField(upload_to='picture')),
                ('teamdesc', models.TextField()),
            ],
        ),
    ]
